name: OpenOSRS - CI (Push)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - name: Download java
        run: wget -O jdk-8u221-linux-x64.tar.gz -c --content-disposition "https://javadl.oracle.com/webapps/download/AutoDL?BundleId=239835_230deb18db3e4014bb8e3e8324f81b43"

      - name: Set up JDK 8
        uses: actions/setup-java@master
        with:
          java-version: 1.8
          architecture: x64
          jdkFile: ./jdk-8u221-linux-x64.tar.gz

      - uses: actions/checkout@v1

      - uses: actions/checkout@v1
        with:
          repository: Owain94/runelite-extended
          ref: externals-rework

      - name: Make gradlew executable (client)
        run: chmod +x ./gradlew
        working-directory: /home/runner/work/plugins/runelite-extended

      - name: Assembling client
        run: ./gradlew assemble --console=plain
        working-directory: /home/runner/work/plugins/runelite-extended

      - name: Building client
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: /home/runner/work/plugins/runelite-extended

      - name: Upload client artifacts to local maven
        run: ./gradlew publishToMavenLocal --console=plain
        working-directory: /home/runner/work/plugins/runelite-extended

      - name: Make gradlew executable (plugins)
        run: chmod +x ./gradlew

      - name: Assembling plugins
        run: ./gradlew assemble --console=plain

      - name: Building plugins
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain

      - name: Testing plugins
        run: ./gradlew test --stacktrace --console=plain
